CREATE OR REPLACE FUNCTION public.current_user_ecosystem_id() RETURNS uuid LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$ DECLARE _ecosystem_id uuid; BEGIN SELECT ecosystem_id INTO _ecosystem_id FROM public.profiles WHERE id=auth.uid(); RETURN _ecosystem_id; END; $$;
GRANT EXECUTE ON FUNCTION public.has_role(uuid,public.app_role), public.current_user_role(), public.is_active_user(uuid), public.current_user_ecosystem_id() TO authenticated,service_role;

ALTER TABLE public.ecosystems ENABLE ROW LEVEL SECURITY; ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY; ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY; ALTER TABLE public.warehouses ENABLE ROW LEVEL SECURITY; ALTER TABLE public.products ENABLE ROW LEVEL SECURITY; ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY; ALTER TABLE public.audit_entries ENABLE ROW LEVEL SECURITY; ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.workspace_settings ENABLE ROW LEVEL SECURITY;
-- Final ecosystem-scoped policies.
DROP POLICY IF EXISTS ecosystems_select_own ON public.ecosystems;
DROP POLICY IF EXISTS profiles_select_own_or_admin ON public.profiles;
DROP POLICY IF EXISTS profiles_update_admin ON public.profiles;
DROP POLICY IF EXISTS user_roles_select_own_or_admin ON public.user_roles;
DROP POLICY IF EXISTS user_roles_insert_admin ON public.user_roles;
DROP POLICY IF EXISTS user_roles_update_admin ON public.user_roles;
DROP POLICY IF EXISTS user_roles_delete_admin ON public.user_roles;
DROP POLICY IF EXISTS warehouses_select_authenticated ON public.warehouses;
DROP POLICY IF EXISTS warehouses_insert_manager_admin ON public.warehouses;
DROP POLICY IF EXISTS warehouses_update_manager_admin ON public.warehouses;
DROP POLICY IF EXISTS warehouses_delete_manager_admin ON public.warehouses;
DROP POLICY IF EXISTS products_select_authenticated ON public.products;
DROP POLICY IF EXISTS products_insert_inventory_roles ON public.products;
DROP POLICY IF EXISTS products_update_inventory_roles ON public.products;
DROP POLICY IF EXISTS products_delete_admin ON public.products;
DROP POLICY IF EXISTS stock_movements_select_inventory_roles ON public.stock_movements;
DROP POLICY IF EXISTS stock_movements_insert_inventory_roles ON public.stock_movements;
DROP POLICY IF EXISTS audit_entries_select_authenticated ON public.audit_entries;
DROP POLICY IF EXISTS transactions_select_cashier_admin_manager ON public.transactions;
DROP POLICY IF EXISTS transactions_insert_cashier_admin ON public.transactions;
DROP POLICY IF EXISTS workspace_settings_select_authenticated ON public.workspace_settings;
DROP POLICY IF EXISTS workspace_settings_update_admin ON public.workspace_settings;
CREATE POLICY ecosystems_select_own ON public.ecosystems FOR SELECT TO authenticated USING(is_active_user(auth.uid()) AND id=current_user_ecosystem_id());
CREATE POLICY profiles_select_own_or_admin ON public.profiles FOR SELECT TO authenticated USING(is_active_user(auth.uid()) AND ecosystem_id=current_user_ecosystem_id() AND (id=auth.uid() OR has_role(auth.uid(),'admin')));
CREATE POLICY profiles_update_admin ON public.profiles FOR UPDATE TO authenticated USING(has_role(auth.uid(),'admin') AND ecosystem_id=current_user_ecosystem_id()) WITH CHECK(has_role(auth.uid(),'admin') AND ecosystem_id=current_user_ecosystem_id());
CREATE POLICY user_roles_select_own_or_admin ON public.user_roles FOR SELECT TO authenticated USING(is_active_user(auth.uid()) AND EXISTS(SELECT 1 FROM public.profiles p WHERE p.id=user_roles.user_id AND p.ecosystem_id=current_user_ecosystem_id()) AND (user_id=auth.uid() OR has_role(auth.uid(),'admin')));
CREATE POLICY user_roles_insert_admin ON public.user_roles FOR INSERT TO authenticated WITH CHECK(has_role(auth.uid(),'admin') AND EXISTS(SELECT 1 FROM public.profiles p WHERE p.id=user_roles.user_id AND p.ecosystem_id=current_user_ecosystem_id()));
CREATE POLICY user_roles_update_admin ON public.user_roles FOR UPDATE TO authenticated USING(has_role(auth.uid(),'admin') AND EXISTS(SELECT 1 FROM public.profiles p WHERE p.id=user_roles.user_id AND p.ecosystem_id=current_user_ecosystem_id())) WITH CHECK(has_role(auth.uid(),'admin') AND EXISTS(SELECT 1 FROM public.profiles p WHERE p.id=user_roles.user_id AND p.ecosystem_id=current_user_ecosystem_id()));
CREATE POLICY user_roles_delete_admin ON public.user_roles FOR DELETE TO authenticated USING(has_role(auth.uid(),'admin') AND EXISTS(SELECT 1 FROM public.profiles p WHERE p.id=user_roles.user_id AND p.ecosystem_id=current_user_ecosystem_id()));
CREATE POLICY warehouses_select_authenticated ON public.warehouses FOR SELECT TO authenticated USING(is_active_user(auth.uid()) AND ecosystem_id=current_user_ecosystem_id());
CREATE POLICY warehouses_insert_manager_admin ON public.warehouses FOR INSERT TO authenticated WITH CHECK(is_active_user(auth.uid()) AND ecosystem_id=current_user_ecosystem_id() AND (has_role(auth.uid(),'admin') OR has_role(auth.uid(),'warehouse_manager')));
CREATE POLICY warehouses_update_manager_admin ON public.warehouses FOR UPDATE TO authenticated USING(is_active_user(auth.uid()) AND ecosystem_id=current_user_ecosystem_id() AND (has_role(auth.uid(),'admin') OR has_role(auth.uid(),'warehouse_manager'))) WITH CHECK(ecosystem_id=current_user_ecosystem_id() AND (has_role(auth.uid(),'admin') OR has_role(auth.uid(),'warehouse_manager')));
CREATE POLICY warehouses_delete_manager_admin ON public.warehouses FOR DELETE TO authenticated USING(is_active_user(auth.uid()) AND ecosystem_id=current_user_ecosystem_id() AND (has_role(auth.uid(),'admin') OR has_role(auth.uid(),'warehouse_manager')));
CREATE POLICY products_select_authenticated ON public.products FOR SELECT TO authenticated USING(is_active_user(auth.uid()) AND ecosystem_id=current_user_ecosystem_id());
CREATE POLICY products_insert_inventory_roles ON public.products FOR INSERT TO authenticated WITH CHECK(is_active_user(auth.uid()) AND ecosystem_id=current_user_ecosystem_id() AND (has_role(auth.uid(),'admin') OR has_role(auth.uid(),'warehouse_manager') OR has_role(auth.uid(),'warehouse_worker')));
CREATE POLICY products_update_inventory_roles ON public.products FOR UPDATE TO authenticated USING(is_active_user(auth.uid()) AND ecosystem_id=current_user_ecosystem_id() AND (has_role(auth.uid(),'admin') OR has_role(auth.uid(),'warehouse_manager') OR has_role(auth.uid(),'warehouse_worker'))) WITH CHECK(ecosystem_id=current_user_ecosystem_id() AND (has_role(auth.uid(),'admin') OR has_role(auth.uid(),'warehouse_manager') OR has_role(auth.uid(),'warehouse_worker')));
CREATE POLICY products_delete_admin ON public.products FOR DELETE TO authenticated USING(is_active_user(auth.uid()) AND ecosystem_id=current_user_ecosystem_id() AND has_role(auth.uid(),'admin'));
CREATE POLICY stock_movements_select_inventory_roles ON public.stock_movements FOR SELECT TO authenticated USING(is_active_user(auth.uid()) AND ecosystem_id=current_user_ecosystem_id() AND (has_role(auth.uid(),'admin') OR has_role(auth.uid(),'warehouse_worker') OR has_role(auth.uid(),'warehouse_manager') OR has_role(auth.uid(),'inspector')));
CREATE POLICY stock_movements_insert_inventory_roles ON public.stock_movements FOR INSERT TO authenticated WITH CHECK(is_active_user(auth.uid()) AND ecosystem_id=current_user_ecosystem_id() AND (has_role(auth.uid(),'admin') OR has_role(auth.uid(),'warehouse_worker') OR has_role(auth.uid(),'warehouse_manager')));
CREATE POLICY audit_entries_select_authenticated ON public.audit_entries FOR SELECT TO authenticated USING(is_active_user(auth.uid()) AND ecosystem_id=current_user_ecosystem_id());
CREATE POLICY transactions_select_cashier_admin_manager ON public.transactions FOR SELECT TO authenticated USING(is_active_user(auth.uid()) AND ecosystem_id=current_user_ecosystem_id() AND (has_role(auth.uid(),'admin') OR has_role(auth.uid(),'cashier') OR has_role(auth.uid(),'warehouse_manager')));
CREATE POLICY transactions_insert_cashier_admin ON public.transactions FOR INSERT TO authenticated WITH CHECK(is_active_user(auth.uid()) AND ecosystem_id=current_user_ecosystem_id() AND (has_role(auth.uid(),'admin') OR has_role(auth.uid(),'cashier')));
CREATE POLICY workspace_settings_select_authenticated ON public.workspace_settings FOR SELECT TO authenticated USING(is_active_user(auth.uid()) AND ecosystem_id=current_user_ecosystem_id());
CREATE POLICY workspace_settings_update_admin ON public.workspace_settings FOR UPDATE TO authenticated USING(has_role(auth.uid(),'admin') AND ecosystem_id=current_user_ecosystem_id()) WITH CHECK(has_role(auth.uid(),'admin') AND ecosystem_id=current_user_ecosystem_id());
ALTER VIEW public.inventory_balances SET(security_invoker=true); ALTER VIEW public.product_stock_summary SET(security_invoker=true);
